//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormsPlayground.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FormsPlayground.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A forms view should have a binding context of type {0}.
        /// </summary>
        public static string CustomNavigationPage_binding_context_type_error {
            get {
                return ResourceManager.GetString("CustomNavigationPage_binding_context_type_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data error.
        /// </summary>
        public static string FeatureListViewModel_Data_error {
            get {
                return ResourceManager.GetString("FeatureListViewModel_Data_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature list has multiple parent nodes with the same id.
        /// </summary>
        public static string FeatureListViewModel_Feature_list_has_multiple_parent_nodes_with_the_same_id {
            get {
                return ResourceManager.GetString("FeatureListViewModel_Feature_list_has_multiple_parent_nodes_with_the_same_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node with title &apos;{0}&apos; needs an Id.
        /// </summary>
        public static string FeatureListViewModel_Node_id_error {
            get {
                return ResourceManager.GetString("FeatureListViewModel_Node_id_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node with title &apos;{0}&apos; needs a {1}.
        /// </summary>
        public static string FeatureListViewModel_ViewModelType_error {
            get {
                return ResourceManager.GetString("FeatureListViewModel_ViewModelType_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument is null or empty.
        /// </summary>
        public static string Ioc_Bootstrap_Argument_is_null_or_empty {
            get {
                return ResourceManager.GetString("Ioc_Bootstrap_Argument_is_null_or_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design.
        /// </summary>
        public static string Menu_Design {
            get {
                return ResourceManager.GetString("Menu_Design", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forms.
        /// </summary>
        public static string Menu_Forms {
            get {
                return ResourceManager.GetString("Menu_Forms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Libs.
        /// </summary>
        public static string Menu_Libs {
            get {
                return ResourceManager.GetString("Menu_Libs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Misc.
        /// </summary>
        public static string Menu_More {
            get {
                return ResourceManager.GetString("Menu_More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skia.
        /// </summary>
        public static string Menu_Skia {
            get {
                return ResourceManager.GetString("Menu_Skia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View must be of type Page.
        /// </summary>
        public static string PageBuilder_View_type_exception {
            get {
                return ResourceManager.GetString("PageBuilder_View_type_exception", resourceCulture);
            }
        }
    }
}
